---
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
# Hub 정보
hub_info:
  name: "n4000"
  public_key: "SIb8eIm+y9dUq5erNdBQgKYbce084KsFa/nnUiGn4j0="
  endpoint: "yeopeter1031.mooo.com:11052"

# 모든 Peer 리스트 (Hub 설정 생성용)
all_peers:
  - { name: "arm", ip: "10.0.1.1", pub: "JOdISmFFJVQbVEB14jl3J8hFWReKFQ0DDT6h4t0bHhs=" }
  - { name: "s10", ip: "10.0.1.2", pub: "vewOBQlw6ZM/Ns4v3b5+MiG9+gSP9e9Uqj72XJP6LSY=" }
  - { name: "tab", ip: "10.0.1.3", pub: "aRHv1vnUM/lTsGC1nSBWuK5a7LpAlodjC8FcSekXABA=" }
  - { name: "mom_phone", ip: "10.0.1.4", pub: "yJf+E9TonCwnkwtBX1J/99VBnZ/xOxPTIK0TGaKbSV4=" }
  - { name: "dad_phone", ip: "10.0.1.5", pub: "dteTQIlcIhUYNQGgxr7LT18h9hpqOV1bQV8FgJhfeAI=" }
  - { name: "my_phone", ip: "10.0.1.6", pub: "mLjLyZeecrVCXSE9DsPCf4XtNwtFFt5S7SsjS017SQE=" }
  - { name: "vps", ip: "10.0.1.9", pub: "fIoIbYGkELkxqRY392XJb29TXhAnhVRwwfC8E2FnJjU=" }
  - { name: "n4000", ip: "10.0.1.10", pub: "SIb8eIm+y9dUq5erNdBQgKYbce084KsFa/nnUiGn4j0=" }
  - { name: "n4200", ip: "10.0.1.11", pub: "v8wip4YhfP+1uL2JQBMsddy6dlEzhn6eE/KDgHqF2z0=" }
  - { name: "my_pc", ip: "10.0.1.100", pub: "3J0soGzcZMPDs0gDMGBO1syjcdbsEKaxmzU/pCapqQE=" }
  - { name: "mac", ip: "10.0.1.105", pub: "esssRW/Tqm4k6pL9jt3fyyYdmtxgQe/JjDkNoDyTgXs=" }

# 호스트별 변수
# site.yml 첫 플레이 pre_tasks에서 이 값을 각 호스트 fact로 적용함
host_specific:
  arm:
    endpoint: "arm.yeoun.org:51820"
    public_key: "JOdISmFFJVQbVEB14jl3J8hFWReKFQ0DDT6h4t0bHhs="
    private_key: "oETakFSYYm5apBOMEs8gd5OP6nhM2H0TWPpf3bW4DnA="
    address: "10.0.1.1"
    public_interface: "enp6s0"
  vps:
    endpoint: "168.107.21.127:51820"
    public_key: "fIoIbYGkELkxqRY392XJb29TXhAnhVRwwfC8E2FnJjU="
    private_key: "sNzNwznoUnyNajQLU/jYkOJmBLUFaXNURKGuOn6WDVY="
    address: "10.0.1.9"
    public_interface: "ens3"
  n4000:
    endpoint: "yeopeter1031.mooo.com:11052"
    public_key: "SIb8eIm+y9dUq5erNdBQgKYbce084KsFa/nnUiGn4j0="
    private_key: "OMqz61cYRRTeeWlzR5byM4623SQsObk+M3WFn6J6nl8="
    address: "10.0.1.10"
    public_interface: "enp2s0"
  n4200:
    endpoint: "yeopeter1031.mooo.com:11053"
    public_key: "v8wip4YhfP+1uL2JQBMsddy6dlEzhn6eE/KDgHqF2z0="
    private_key: "8PvaE6F78QxQDA6mwmX+p7TBrg0zS+ZxL8ES5r8X/kA="
    address: "10.0.1.11"
    public_interface: "wlp1s0"

# tailscale network configuration
vault_tailscale_auth_key: "tskey-auth-kA8RUzQDAf11CNTRL-zEoPAERbcei3Ljnk5VGSfi93DANUdxmF"