---
# 1. [Init] 로컬 SSD에 서비스 담을 폴더 생성
- name: Ensure Local Service Directory exists
  file:
    path: "{{ local_service_path }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop: "{{ target_services }}"



# [수정 후: 확실한 방법 (rsync 직접 호출)]
- name: Stat Source Service Directory
  stat:
    path: "{{ wg_nfs_client_mount_path }}/docker_volumes/{{ item }}/"
  register: source_dir_stats
  loop: "{{ target_services }}"

- name: Check pending updates from NFS to Local
  command: "rsync -ani --update {{ wg_nfs_client_mount_path }}/docker_volumes/{{ item }}/ {{ local_service_path }}/{{ item }}/"
  register: sync_check_results
  changed_when: false
  loop: "{{ target_services }}"
  loop_control:
    index_var: svc_index
  when:
    - source_dir_stats.results[svc_index].stat.exists

- name: Sync missing files from NFS to Local without overwrite
  command: "rsync -a --ignore-existing {{ wg_nfs_client_mount_path }}/docker_volumes/{{ item }}/ {{ local_service_path }}/{{ item }}/"
  loop: "{{ target_services }}"
  loop_control:
    index_var: svc_index
  when:
    - source_dir_stats.results[svc_index].stat.exists
