[oci_nodes]
arm    ansible_host=arm.yeoun.org              ansible_user=ubuntu ansible_port=22

[home_nodes]
n4000  ansible_host=yeopeter1031.mooo.com      ansible_user=yeoun  ansible_port=11022
n4200  ansible_host=yeopeter1031.mooo.com      ansible_user=yeoun  ansible_port=11023

[tmp_nodes]
n4200
arm
