[oci_nodes]
arm    ansible_host=10.0.1.1  ansible_user=ubuntu

[home_nodes]
n4000      ansible_host=10.0.1.10 ansible_user=yeoun
n4200      ansible_host=10.0.1.11 ansible_user=yeoun

[tmp_nodes]
n4200
arm
