---
- name: Run base system setup
  ansible.builtin.import_tasks: base.yml

- name: Run Docker setup
  ansible.builtin.import_tasks: docker.yml

- name: Run SSH security policy
  ansible.builtin.import_tasks: security.yml
