---
- name: Start Docker service
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure Docker service is enabled and started
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
